photo/urls.py
from django.conf.urls import include, url
from photo.settings import URL_SRCH_DLMTR
from photo import views

urlpatterns = [
    url(r'^$', views.show_albums, name='photo.views.show_albums'),
    url(r'^(?P<page_id>\d+)/$', views.show_albums, name='photo.views.show_albums'),
    url(r'^t/(?P<filter>[\w\-\_{0}]+)/$'.format(URL_SRCH_DLMTR), views.show_albums, name='photo.views.show_albums'),
    url(r'^t/(?P<filter>[\w\-\_{0}]+)/(?P<page_id>\d+)/$'.format(URL_SRCH_DLMTR), views.show_albums, name='photo.views.show_albums'),
    url(r'^a/(?P<view>f|t)/(?P<album_id>\d+)/.*$', views.show_album, name='photo.views.show_album'),
    url(r'^a/c/(?P<album_id>\d+)/dumb.js$', views.count_album, name='photo.views.count_album'),
    url(r'^g/(?P<link_name>[\w\-\_]+)/$', views.show_go, name='photo.views.show_go'),
    url(r'^categories/$', views.show_categories, name='photo.views.show_categories'),
    url(r'^contact/$', views.show_contact, name='photo.views.show_contact'),
    url(r'^t/$', views.show_all_tags, name='photo.views.show_all_tags'),
]

photo/forms.py
from django import forms
from photo.models import Tag
from django.contrib.admin.widgets import FilteredSelectMultiple

class AddTagForm(forms.Form):
    _selected_action = forms.CharField(widget=forms.MultipleHiddenInput)
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=FilteredSelectMultiple('tags', False))
    act = forms.ChoiceField(choices = (('add', 'add'), ('remove', 'remove')), label = 'Action')
    class Media:
        extend = False
        css = { 'all':[
              'admin/css/forms.css',
              'admin/css/widgets.css',
              ]
              }
        js = [
             'admin/js/core.js',
             '/static/admin/js/admin/RelatedObjectLookups.js',
             'admin/js/jquery.js',
             'admin/js/jquery.init.js',
             'admin/js/SelectBox.js',
             'admin/js/SelectFilter2.js',
             '/admin/jsi18n/',
             ]

class RenameForm(forms.Form):
    _selected_action = forms.CharField(widget=forms.MultipleHiddenInput)
    find = forms.CharField(label='Find string', required=True)
    replace = forms.CharField(label='Replace with', required=False)
    only_name = forms.BooleanField(label='Change only name (preserves URL, JSON description, etc.)', required = False)

class AddAlbumForm(forms.Form):
    path = forms.CharField(label='From path', required=True)
    url = forms.CharField(label='From url', required=False)

class ContactForm(forms.Form):
    name = forms.CharField(label='Your name', required=True, max_length=32, widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(label='Your e-mail', required=True, max_length=32, widget=forms.TextInput(attrs={'class':'form-control'}))
    subject = forms.CharField(label='Subject', required=True, max_length=128, widget=forms.TextInput(attrs={'class':'form-control'}))
    message = forms.CharField(label='Message', required=True, max_length=2048, widget=forms.Textarea(attrs={'class':'form-control'}))

photo/templates/admin_action_add_tag.html
{% extends "admin/base_site.html" %}
{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
   <a href="{% url 'admin:index' %}">Home</a> ›
   <a href="{% url 'admin:app_list' 'photo' %}">Photo</a> ›
   <a href="{% url 'admin:photo_album_changelist' %}">Albums</a> ›
   Add/Remove tags
</div>
{% endblock %}

{% block content %}
<h1>Add/Remove tags</h1>
<form action="" method="post">{% csrf_token %}
<fieldset class="module aligned">
   <div class="form-row field-tags">
       <p><a href="{% url 'admin:photo_tag_add' %}" class="add-another" id="add_id_tags" onclick="return showAddAnotherPopup(this);"> <img src="/static/admin/img/icon_addlink.gif" width="10" height="10" alt="Add Another"></a></p>
         {{ form.as_p }}
   </div>
   <div class="form-row field-tags">
      <p>Tags will be added to or removed from the following albums:</p>
      <ul>{{ items|unordered_list }}</ul>
   </div>
   <div class="form-row field-tags">
      <input type="hidden" name="action" value="add_tags" />
      <input type="submit" name="submit" value="Go" class="default"/>
   </div>
</fieldset>
</form>
{% endblock %}

photo/templates/admin_action_rename.html
{% extends "admin/base_site.html" %}
{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
   <a href="{% url 'admin:index' %}">Home</a> ›
   <a href="{% url 'admin:app_list' 'photo' %}">Photo</a> ›
   Rename
</div>
{% endblock %}

{% block content %}
<h1>Rename</h1>
<form action="" method="post">{% csrf_token %}
<fieldset class="module aligned">
   <div class="form-row field-tags">
         {{ form.as_p }}
   </div>
   <div class="form-row field-tags">
      <input type="hidden" name="action" value="rename" />
      <input type="submit" name="submit" value="Rename" class="default" />
   </div>
</fieldset>
</form>
{% endblock %}

photo/templates/admin_albums_add.html
{% extends 'admin/base_site.html' %}

{% block extrastyle %}
<style> 
<!--
#id_path { width: 500px; }
#id_url { width: 500px; }
#id_submit { width: 500px; }
-->
</style>
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
   <a href="{% url 'admin:index' %}">Home</a> ›
   <a href="{% url 'admin:app_list' 'photo' %}">Photo</a> ›
   <a href="{% url 'admin:photo_album_changelist' %}">Albums</a> ›
   <a href="{% url 'photo.views.admin_albums_add' %}">Add</a>
</div>
{% endblock %}
{% block content %}
<div class="main">
   {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

   <h1>Add albums</h1>
   <form action="{% url 'photo.views.admin_albums_add' %}" method="post"> {% csrf_token %}
      <table>
       {{ form }}
       <tr><th></th><td>
       <input type="submit" value="Add" id="id_submit" /> 
       </td></tr>
      </table>
   </form>
</div>
{% endblock %}

photo/templates/admin_albums_add_result.html
{% extends 'admin_albums_add.html' %}

{% block content %}

<div class="main" align="center">
   {% autoescape off %}
   {% if dbg %}<p><strong>DEBUG: {{ dbg }}</strong></p>{% endif %}
   {% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
   {% endautoescape%}

   <div align="center">
      <div style = "float:left; width: 130px; padding:1% 0% 0% 38%">
      <form action="{% url 'photo.views.admin_albums_add' %}" method="get">
         {% csrf_token %}
         <input type="submit" value="Add more" style="width: 125px;" />
      </form>
      </div>
   
      <div style = "float:left; width: 130px; padding: 1%">
      <form action="{% url 'admin:photo_album_changelist' %}" method="post">
         {% csrf_token %}
         <input type="submit" value="Moderate" style="width: 125px;" />
      </form>
      </div>
   <div style = "clear:both"></div>
   </div>

</div>

{% endblock %}

photo/templates/base.html
{% load photo_galleryname %}
{% load photo_ad %}
{% load photo_menus %}
{% photo_menu_main_as as photo_menu_main %}
{% photo_menu_footer_as as photo_menu_footer %}
{% photo_alert_as as photo_alert %}
{% photo_popup_as as photo_popup %}
{% photo_hist_link_as as photo_hist_link %}
{% load cache %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content={% block description %}""{% endblock %} />
    <meta name="author" content="">
    <link rel="icon" href="/favicon.ico">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,500' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/static/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css" >
    <title>{% block title %}{% photo_galleryname %}{% endblock %}</title>
    {% block extrahead %}
    {% endblock %}
  </head>

  <body>
    {% cache 600 navsidebar %}
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    {% if photo_alert.enabled %}
      <div class="alert alert-{{ photo_alert.class }} alert-dismissible cookie-law centered" role="alert" id="cookie-law">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        {{ photo_alert.text|safe }} <a id="cookie-law-btn" class="btn btn-{{ photo_alert.class }}" href="{{ photo_alert.link|safe }}" target="_blank" rel="nofollow" {#onclick="$('#cookie-law').alert('close');"#} >{{ photo_alert.button|safe }}</a>
      </div>
    {% endif %}
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed gl-btn" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
            <!-- span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span-->
          </button>
          <a href="#menu-toggle" class="navbar-toggle gl-btn" id="menu-toggle">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        </a>
          <a class="navbar-brand" href="/">{% photo_galleryname %}</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% for m in photo_menu_main %}
            <li {{m.li_attributes|safe }} ><a href="{{ m.link|safe }}" {{ m.attributes|safe }}><span class="glyphicon {{ m.glyphicon }}"></span> {{ m.name|safe }}</a></li>
            {% endfor %}
            {% comment %}
            {% if user.is_staff %}
              {% block admin_menu %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
              {% endblock %}
            {% endif %}
            {% endcomment %}
          </ul>
        </div>
      </div>
    </nav>

    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            {# <li class="sidebar-brand"> <a href="/t/Tags/"> <span class="glyphicon glyphicon-tags"></span> {{ menu.0.0.name }}</a></li> #}
            {% for item in menu.0|slice:"1:" %}
              <li> <a href="{% url 'photo.views.show_albums' filter=item.name %}">{{ item.name|title }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <!-- /#sidebar -->
    {% endcache %}

    <div class="container centered" id="wrapper">
    {% cache 600 bd_ca view_name %}
      {% photo_ad "bd_ca" view_name %}
    {% endcache %}
      {% block content %}{% endblock %}
    {% cache 600 bd_cb view_name %}
      {% photo_ad "bd_cb" view_name %}
    {% endcache %}
    </div>

    {% cache 600 footer %}
    <footer class="footer">
      <div class="container">
        <p class="text-muted">
          {% for m in photo_menu_footer %}
            <a href="{{ m.link|safe }}" {{ m.attributes|safe }}>{{ m.name|safe }}</a>
          {% endfor %}
        </p>
      </div>
    </footer>
    {% endcache %}

    {% cache 600 bd_foo view_name %}
    {% photo_ad "bd_foo" view_name %}
    {% endcache %}

    {% cache 600 below_footer %}
    <script src="/static/jquery/1.11.1/jquery.min.js"></script>
    <script src="/static/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>
    <script type="text/javascript">
        function SetBodyPadding(){
            $(document.body).css('padding-top', $('.navbar').height());
            $('#sidebar-wrapper').css('top', $('.navbar').height());
        }
        $(document).ready(function(){
          {% if photo_alert.enabled %}
            if (document.cookie.indexOf("cookie-law") < 0) {
                $('#cookie-law').css('display', 'block');
            }
            SetBodyPadding();
          {% endif %}
          {% if photo_hist_link.enabled %}
            if (document.cookie.indexOf("non-first-page") < 0) {
              document.cookie="non-first-page=true;max-age=86400;path=/;"; 
              var sec = new Date().getSeconds();
              if (sec % 10  < {{ photo_hist_link.fraction|safe }}) {
                if (window.history && window.history.pushState) {
                  $(window).on('popstate', function() {
                    if (location.hash.split("#!/")[1] !== '') {
                      if (window.location.hash === '') {
                        window.location='{{ photo_hist_link.link|safe }}';
                        return false;
                      }
                    }
                  });
                  window.history.pushState('forward', null, location.pathname);
                }
              }
            }
          {% endif %}
        });
        {% if photo_alert.enabled %}
          $('#cookie-law').on('closed.bs.alert', function() {
            SetBodyPadding();
            document.cookie="cookie-law=true;max-age=86400;path=/;"; 
          });
        {% endif %}
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
            $("#sidebar-wrapper").toggleClass("toggled");
            $("footer").toggleClass("toggled");
            SetBodyPadding();
        });
    </script>
    {% if photo_popup.enabled %}
        <div class="dpop" id="dpop">
            {% if photo_popup.close_button %}
                <div>
                    <button type="button" class="close" onclick="DpopClose();"><span aria-hidden="true">&times;</span></button>
                </div>
            {% endif %}
            {{ photo_popup.code|safe }}
        </div>
        <script type="text/javascript">
            function DpopClose(){
                $('#dpop').css('display', 'none');
                document.cookie="dpop=true;max-age=86400;path=/;"; 
            }
            $(document).ready(function(){
                if (document.cookie.indexOf("dpop") < 0) {
                    $('#dpop').css('display', 'block');
                }
            });
        </script>
    {% endif %}

    {% include 'google_analitics.html' %}
    {% endcache %}
  </body>
</html>

photo/templates/google_analitics.html
{% load photo_ga %}
{% photo_ga_enabled as ga_enabled %}
{% if ga_enabled %}
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '{% photo_ga_id %}', '{% photo_ga_site %}');
  ga('send', 'pageview');
</script>
{% endif %}

photo/templates/show_album.html
{% extends "base.html" %}
{% load photo_ad %}
{% load cache %}
{% comment %}
{% load photo_share_buttons %}
{% endcomment %}

{% block description %}"{{ description|capfirst }}"{% endblock %} 
{% block title %}{{ title|capfirst }}{% endblock %} 

{% block extrahead %}
   {% if views_count %} <script async src="/a/c/{{ album.id }}/dumb.js"></script> {% endif %}
   <meta name="plugz:title" content="{{ album.name }}" />          
   <meta name="plugz:tags" content="{{ album.tags_as_str }}"/>
   <meta name="plugz:imgurl" content="{{ images.first.get_full_image_url }}" />  
   <meta name="plugz:pageurl" content="{{ album.get_full_absolute_url }}" /> 
   <meta name="plugz:contenttype" content="IMAGE"/>  
{% endblock %}

{% block admin_menu %}
{{ block.super }}
<li><a href="{% url 'admin:photo_album_change' album.id %}">Change album</a></li>
{% endblock %}

{% block content %}
<h1 class="album_title">{{ album.name }}</h1>
{% comment %}
{% if show_icons %}
   <div class="view">
       <a href="{{ album.get_absolute_url_t }}"><span class="glyphicon glyphicon-th"></span></a>
       <a href="{{ album.get_absolute_url_f }}"><span class="glyphicon glyphicon-align-justify"></span></a>&nbsp;
   </div>
{% endif %}
{% endcomment %}
{% if tags %}
   <div class="tags">
   {% for group in tags %}
      <div class="tag_group">
      {% for item in group %}
         {% if forloop.first %}{{ item.name }}:
         {% else %}&#160;<a href="{% url 'photo.views.show_albums' filter=item.name %}" >{{ item.name }}</a>
         {% endif %}
      {% endfor %}
      </div>
   {% endfor %}
   </div>
{% endif %}
{% comment %}
{% sb_top_as as sb_top %}
{% if sb_top %}
    {% photo_share_buttons album.get_absolute_url album.name images.first.image.url %}
{% endif %}
{% if view == "f" %}
{% endcomment %}
{% for img in images %}
   <figure class="photo">
   {% if image_link %}
      <a href="{{ image_link }}" target="_blank" >
   {% else %}
      <a href="{{ img.image.url }}" target="_blank" >
   {% endif %}
   <img class="img-rounded full" alt="{{ album.name }}" src="{{ img.image.url }}" width="{{ img.image.width }}" height="{{ img.image.height }}" />
   </a>
   {% if forloop.first %} <figcaption>{{ album.name }}</figcaption> {% endif %}
   </figure>
{% if forloop.first %}
{% if album.description %}
   <div class="description">
      {{ album.description|safe }}
   </div>
{% endif %}
{% cache 600 bd_ci_sa view_name %}
   {% photo_ad "bd_ci_sa" view_name %}
{% endcache %}
{% endif %}
{% empty %}
   <p>No photos found</p>
{% endfor %}
{% comment %}
{% else %}
{% for img in images %}
         <a href="{{ img.image.url }}" >
         <img class="img-rounded thumbnail" alt="{{ album.name }}" src="{{ img.thumbnail.url }}" width="{{ img.thumbnail.width }}" height="{{ img.thumbnail.height }}" />
         </a>
      {% if forloop.counter in ad_pos %}
         {% photo_ad "bd_ci1" view_name %}
      {% endif %}
{% empty %}
   <p>No photos found</p>
{% endfor %}
{% endif %}
{% if bottom_tags and tags %}
   <div class="tags">
   {% for group in tags %}
      <div class="tag_group">
      {% for item in group %}
         {% if forloop.first %} <a class="tag_group" href="{% url 'photo.views.show_albums' filter=item.name %}" >{{ item.name }}</a>:
         {% else %}             <a href="{% url 'photo.views.show_albums' filter=item.name %}" >{{ item.name }}</a>
            {% if not forloop.last %}&#160;{% endif %}
         {% endif %}
      {% endfor %}
      </div>
   {% endfor %}
   </div>
{% endif %}
{% sb_bottom_as as sb_bottom %}
{% if sb_bottom %}
    {% photo_share_buttons album.get_absolute_url album.name images.first.image.url %}
{% endif %}
{% endcomment %}
{% cache 5 similar_albums %}
{% if similar_albums %}
   {% if similar_albums_header %}
   <hr />
   <div class="similar_albums_header">{{ similar_albums_header }}</div>
   {% endif %}
   <div class="albums">
   {% for album in similar_albums %}
      <div class="album">
         <div class="title">
            <a href="{{ album.get_absolute_url }}" rel="nofollow" >{{ album.name }}</a>
         </div>
      <a href="{{ album.get_absolute_url }}" rel="nofollow"><img class="img-rounded" alt="{{ album.name }}"
        src="{{ album.cover.thumbnail.url }}" width="{{ album.cover.thumbnail.width }}" height="{{ album.cover.thumbnail.height }}" /></a>
      </div>
   {% endfor %}
   </div>
   <nav class="paginator">
   <a class="btn btn-primary" href="{% url 'photo.views.show_albums' %}">{{ pagination_btn_text }}</a>
   {% if special_button.enabled %}
   <a class="btn {{ special_button.class }}" href="{{ special_button.link }}" rel="nofollow" target="_blank"><span class="glyphicon {{ special_button.glyphicon }}"></span> {{ special_button.text }}</a>
   {% endif %}
   </nav>
{% endif %}
{% endcache %}

{% endblock %}

photo/templates/show_albums.html
{% extends "base.html" %}
{% load photo_ad %}
{% load cache %}
{% block description %}"{{ description|capfirst }}"{% endblock %}
{% block title %}{{ title|capfirst }}{% endblock %}

{% block admin_menu %}
   {{ block.super }}
   {% if menu_tag  %}
     <li><a href="{% url 'admin:photo_tag_change' menu_tag.id %}">Change tag</a></li>
   {% else %}
     <li><a href="{% url 'admin:photo_album_changelist' %}">Edit albums</a></li>
   {% endif %}
{% endblock %}

{% block content %}
{% if page_h1 %}
   <h1 class="tag_title">{{page_h1|title}}</h1>
{% endif %}

<div class="albums">
{% for album in albums %}
    <div class="album">
        <div class="title"> <a href="{{ album.get_absolute_url }}">{{ album.name }}</a> </div>
        <div class="view">
            {% if show_icons %}
                <a href="{{ album.get_absolute_url_t }}"><span class="glyphicon glyphicon-th"></span></a>
                <a href="{{ album.get_absolute_url_f }}"><span class="glyphicon glyphicon-align-justify"></span></a>&nbsp;
            {% endif %}
        </div>
        <a href="{{ album.get_absolute_url }}"><img class="img-rounded" alt="{{ album.name }}"
        src="{{ album.cover.thumbnail.url }}" width="{{ album.cover.thumbnail.width }}" height="{{ album.cover.thumbnail.height }}" /></a>
    </div>
    {% if forloop.counter in ad_pos %}
    {% cache 600 bd_ci_sas view_name %}
        {% photo_ad "bd_ci_sas" view_name %}
    {% endcache %}
    {% endif %}
{% empty %}
    No albums found
{% endfor %}
</div>

{% comment %}
<div class="paginator">
   <ul class="pagination">
      {% if albums.has_previous %}
         {% if filter %}  <li><a href="{% url 'photo.views.show_albums' filter=filter %}{{ albums.previous_page_number }}/">&laquo;</a></li>
         {% else %}      <li><a href="{% url 'photo.views.show_albums' %}{{ albums.previous_page_number }}/">&laquo;</a></li>
         {% endif %}
      {% endif %}
      {% for page in albums.show_pages %}
         {% if page == albums.number %}
            <li class="active"><a href="">{{ albums.number }}<span class="sr-only">(current)</span></a></li>
         {% elif page == 0 %}
           <li class="disabled"><a href="#">...</a></li>
         {% else %}
            {% if filter %} <li><a href="{% url 'photo.views.show_albums' filter=filter %}{{ page }}/">{{ page }}</a></li>
            {% else %}     <li><a href="{% url 'photo.views.show_albums' %}{{ page }}/">{{ page }}</a></li>
            {% endif %}
         {% endif %}
      {% endfor %}
      {% if albums.has_next %}
         {% if filter %} <li><a href="{% url 'photo.views.show_albums' filter=filter %}{{ albums.next_page_number }}/">&raquo;</a></li>
         {% else %}      <li><a href="{% url 'photo.views.show_albums' %}{{ albums.next_page_number }}/">&raquo;</a></li>
         {% endif %}
      {% endif %}
   </ul>
</div>
{% endcomment %}
<nav class="paginator">
{% if albums.has_next %}
{% if filter %} <a class="btn btn-primary" href="{% url 'photo.views.show_albums' filter=filter %}{{ albums.next_page_number }}/">{{ pagination_btn_text }}</a>
{% else %}      <a class="btn btn-primary" href="{% url 'photo.views.show_albums' %}{{ albums.next_page_number }}/">{{ pagination_btn_text }}</a>
{% endif %}
{% endif %}
{% if special_button.enabled %}
<a class="btn {{ special_button.class }}" href="{{ special_button.link }}" rel="nofollow" target="_blank"><span class="glyphicon {{ special_button.glyphicon }}"></span> {{ special_button.text }}</a>
{% endif %}
</nav>
{% endblock %}

photo/templates/show_all_tags.html
{% extends "base.html" %}
{% load photo_galleryname %}
{% block keywords %}"tags"{% endblock %}
{% block description %}"All {% photo_galleryname %} tags"{% endblock %}
{% block title %}All tags - {% photo_galleryname %}{% endblock %}
{% block extrahead %}
    <meta name="robots" content="noindex, follow"/>
{% endblock %}

{% block admin_menu %}
   {{ block.super }}
     <li><a href="{% url 'admin:photo_tag_changelist' %}">Edit tags</a></li>
{% endblock %}

{% block content %}
{% for group in tags %}
   {% for item in group %}
      {% if forloop.first %}
         <h4 class="text-left"><a href="{% url 'photo.views.show_albums' filter=item.name %}" >{{ item.name }}</a>:</h4>
         <ul class="text-left">
      {% endif %}
      {% if not forloop.first %}
         <li><a href="{% url 'photo.views.show_albums' filter=item.name %}" >{{ item.name }}</a></li>
      {% endif %}
   {% endfor %}
         </ul>
{% endfor %}
{% endblock %}

photo/templates/show_categories.html
{% extends "base.html" %}
{% load photo_galleryname %}
{% block keywords %}"categoties,tags"{% endblock %}
{% block description %}"search in {% photo_galleryname %} categories"{% endblock %}
{% block title %}Categories - {% photo_galleryname %}{% endblock %}

{% block admin_menu %}
   {{ block.super }}
     <li><a href="{% url 'admin:photo_tag_changelist' %}">Edit tags</a></li>
{% endblock %}


{% block content %}
<h4 class="search">Use the form below to find photos with several particular tags</h4>
<form role="form" method="post" action="{% url 'photo.views.show_categories' %}" id="categories">
{% csrf_token %}
   {% for group in tags %}
      <div class="panel panel-default search">
      {% for item in group %}
         {% if forloop.first %}
            <div class="panel-heading"><a href="{% url 'photo.views.show_albums' filter=item.name %}" >{{ item.name }}</a></div>
            <div class="panel-body">
            <div class="search_tags">
         {% endif %}
         {% if not forloop.first %}
            <div class="checkbox">
               <label>
                  <input type="checkbox" name="tag" value="{{ item.name }}"/>
                  {{ item.name }}
               </label>
            </div>
         {% endif %}
      {% endfor %}
      </div>
      </div>
      </div>
   {% endfor %}
<button type="submit" class="btn btn-default search">Search</button>
</form>
{% endblock %}

photo/templates/skel.html
{% extends "base.html" %}

{% block keywords %}"contact"{% endblock %}
{% block description %}"Contact us"{% endblock %} 
{% block title %}Contact us{% endblock %} 

{% block extrahead %}
{% endblock %}

{% block admin_menu %}
{{ block.super }}
{% endblock %}

{% block content %}

{% endblock %}